# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
  batch: true

pool:
  vmImage: "ubuntu-latest"

steps:
  - script: |
      dotnet publish $(System.DefaultWorkingDirectory)/Sheaft.Identity/Sheaft.Identity.csproj -c Release --output publish_output/Sheaft.Identity/sprint/
  - task: DeleteFiles@1
    displayName: "Delete NewRelic"
    inputs:
      SourceFolder: '$(System.DefaultWorkingDirectory)/publish_output/Sheaft.Identity/sprint/newrelic'
      Contents: '*'
  - task: ArchiveFiles@2
    displayName: "Archive files"
    inputs:
      rootFolderOrFile: "$(System.DefaultWorkingDirectory)/publish_output/Sheaft.Identity/sprint"
      includeRootFolder: false
      archiveFile: "$(System.DefaultWorkingDirectory)/publish_output/Sheaft.Identity/build$(Build.BuildId)-sprint.zip"
  - task: PublishBuildArtifacts@1
    displayName: "Publish"
    inputs:
      PathtoPublish: '$(System.DefaultWorkingDirectory)/publish_output/Sheaft.Identity/build$(Build.BuildId)-sprint.zip'
      artifactName: 'sheaft-identity-sprint'